@if($editing)
    <div class="mb-3"><label class="form-label" for="name">Ime i prezime</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $student->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
@else
    <div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="first_name">Ime</label><input class="form-control @error('first_name') is-invalid @enderror" id="first_name" name="first_name" value="{{ old('first_name') }}" required>@error('first_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label class="form-label" for="last_name">Prezime</label><input class="form-control @error('last_name') is-invalid @enderror" id="last_name" name="last_name" value="{{ old('last_name') }}" required>@error('last_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
@endif
<div class="row" @unless($editing) data-student-email-generator data-email-domain="{{ config('app.email_domain') }}" @endunless><div class="col-md-6 mb-3"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" value="{{ old('email', $editing ? $student->email : '') }}" @required($editing)>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror @unless($editing)<div class="form-text">Automatski predlog na domenu &#64;{{ config('app.email_domain') }} može se izmeniti.</div>@endunless</div><div class="col-md-6 mb-3"><label class="form-label" for="index_number">Broj indeksa</label><input class="form-control @error('index_number') is-invalid @enderror" id="index_number" name="index_number" value="{{ old('index_number', $editing ? $student->studentProfile->index_number : '') }}" required>@error('index_number')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="row"><div class="col-md-4 mb-3"><label class="form-label" for="study_level">Nivo studija</label><select class="form-select" id="study_level" name="study_level">@foreach(\App\Enums\StudyLevel::cases() as $level)<option value="{{ $level->value }}" @selected(old('study_level', $editing ? $student->studentProfile->study_level->value : '') === $level->value)>{{ $level->label() }}</option>@endforeach</select></div><div class="col-md-4 mb-3"><label class="form-label" for="study_year">Godina studija</label><input class="form-control @error('study_year') is-invalid @enderror" id="study_year" name="study_year" type="number" min="1" max="4" value="{{ old('study_year', $editing ? $student->studentProfile->study_year : 1) }}" required>@error('study_year')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-4 mb-3"><label class="form-label" for="is_active">Status naloga</label><select class="form-select" id="is_active" name="is_active"><option value="1" @selected(old('is_active', $editing ? (int) $student->is_active : 1) == 1)>Aktivan</option><option value="0" @selected(old('is_active', $editing ? (int) $student->is_active : 1) == 0)>Neaktivan</option></select></div></div>
@unless($editing)
    <div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="password">Inicijalna lozinka</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" required>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-4"><label class="form-label" for="password_confirmation">Potvrda lozinke</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" required></div></div>
@endunless
