@if($editing)
<div class="mb-3"><label class="form-label" for="name">Ime i prezime</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $professor->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
@else
<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="first_name">Ime</label><input class="form-control @error('first_name') is-invalid @enderror" id="first_name" name="first_name" value="{{ old('first_name') }}" required>@error('first_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label class="form-label" for="last_name">Prezime</label><input class="form-control @error('last_name') is-invalid @enderror" id="last_name" name="last_name" value="{{ old('last_name') }}" required>@error('last_name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
@endif
<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="email">Email</label><input class="form-control @error('email') is-invalid @enderror" id="email" name="email" type="email" placeholder="ime.prezime@ftnkm.rs" value="{{ old('email', $editing ? $professor->email : '') }}" required>@error('email')<div class="invalid-feedback">{{ $message }}</div>@enderror<div class="form-text">Adresa mora pripadati domenu &#64;{{ config('app.email_domain') }}.</div></div><div class="col-md-6 mb-3"><label class="form-label" for="academic_title">Akademsko zvanje</label><input class="form-control @error('academic_title') is-invalid @enderror" id="academic_title" name="academic_title" value="{{ old('academic_title', $editing ? $professor->professorProfile->academic_title : '') }}" required>@error('academic_title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div></div>
<div class="row"><div class="col-md-8 mb-3"><label class="form-label" for="department">Katedra</label><input class="form-control" id="department" name="department" value="{{ old('department', $editing ? $professor->professorProfile->department : '') }}"></div><div class="col-md-4 mb-3"><label class="form-label" for="is_active">Status naloga</label><select class="form-select" id="is_active" name="is_active"><option value="1" @selected(old('is_active', $editing ? (int) $professor->is_active : 1) == 1)>Aktivan</option><option value="0" @selected(old('is_active', $editing ? (int) $professor->is_active : 1) == 0)>Neaktivan</option></select></div></div>
<div class="mb-3"><label class="form-label" for="research_area">Oblast interesovanja</label><textarea class="form-control" id="research_area" name="research_area" rows="3">{{ old('research_area', $editing ? $professor->professorProfile->research_area : '') }}</textarea></div>
@unless($editing)<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="password">Inicijalna lozinka</label><input class="form-control @error('password') is-invalid @enderror" id="password" name="password" type="password" required>@error('password')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-4"><label class="form-label" for="password_confirmation">Potvrda lozinke</label><input class="form-control" id="password_confirmation" name="password_confirmation" type="password" required></div></div>@endunless
