@extends('layouts.app')
@section('title', 'Moj profil')
@section('content')
<div class="row justify-content-center"><div class="col-xl-8"><div class="mb-4"><p class="text-primary fw-semibold mb-1">Korisnički nalog</p><h1 class="h2 mb-0">Moj profil</h1></div><form class="card card-body border-0 shadow-sm p-4" method="POST" action="{{ route('profile.update') }}">@csrf @method('PUT')
<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="name">Ime i prezime</label><input class="form-control @error('name') is-invalid @enderror" id="name" name="name" value="{{ old('name', $user->name) }}" required>@error('name')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label class="form-label">Email</label><input class="form-control" value="{{ $user->email }}" disabled><div class="form-text">Email može promeniti administrator.</div></div></div>
@if($user->role === \App\Enums\UserRole::Student)
<div class="row"><div class="col-md-6 mb-3"><label class="form-label">Broj indeksa</label><input class="form-control" value="{{ $user->studentProfile->index_number }}" disabled></div><div class="col-md-6 mb-3"><label class="form-label">Nivo studija</label><input class="form-control" value="{{ $user->studentProfile->study_level->label() }}" disabled></div></div>
<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="date_of_birth">Datum rođenja</label><input class="form-control @error('date_of_birth') is-invalid @enderror" id="date_of_birth" name="date_of_birth" type="date" value="{{ old('date_of_birth', $user->studentProfile->date_of_birth?->format('Y-m-d')) }}" required>@error('date_of_birth')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label class="form-label" for="phone">Telefon</label><input class="form-control" id="phone" name="phone" value="{{ old('phone', $user->studentProfile->phone) }}"></div></div>
<div class="row"><div class="col-md-5 mb-3"><label class="form-label" for="city">Mesto</label><input class="form-control" id="city" name="city" value="{{ old('city', $user->studentProfile->city) }}"></div><div class="col-md-5 mb-3"><label class="form-label" for="address">Adresa</label><input class="form-control" id="address" name="address" value="{{ old('address', $user->studentProfile->address) }}"></div><div class="col-md-2 mb-3"><label class="form-label" for="study_year">Godina</label><input class="form-control" id="study_year" name="study_year" type="number" min="1" max="6" value="{{ old('study_year', $user->studentProfile->study_year) }}"></div></div>
@elseif($user->role === \App\Enums\UserRole::Professor)
<div class="row"><div class="col-md-6 mb-3"><label class="form-label" for="academic_title">Akademsko zvanje</label><input class="form-control @error('academic_title') is-invalid @enderror" id="academic_title" name="academic_title" value="{{ old('academic_title', $user->professorProfile->academic_title) }}" required>@error('academic_title')<div class="invalid-feedback">{{ $message }}</div>@enderror</div><div class="col-md-6 mb-3"><label class="form-label" for="department">Katedra</label><input class="form-control" id="department" name="department" value="{{ old('department', $user->professorProfile->department) }}"></div></div><div class="mb-3"><label class="form-label" for="research_area">Oblast interesovanja</label><textarea class="form-control" id="research_area" name="research_area" rows="4">{{ old('research_area', $user->professorProfile->research_area) }}</textarea></div>
@endif
<div class="d-flex flex-wrap justify-content-between gap-2 mt-2"><a class="btn btn-outline-secondary" href="{{ route('password.change') }}">Promeni lozinku</a><button class="btn btn-primary">Sačuvaj profil</button></div></form></div></div>
@endsection
