@extends('layouts.app')
@section('title', 'Odbrana rada')
@section('content')
<div class="row justify-content-center"><div class="col-xl-8"><div class="mb-4"><p class="text-primary fw-semibold mb-1">Priprema odbrane</p><h1 class="h2">{{ $topic->title }}</h1><p class="text-secondary mb-0">Student: {{ $topic->student->name }} · Mentor: {{ $topic->mentor->name }}</p></div>
<form class="card card-body border-0 shadow-sm p-4" method="POST" action="{{ route('topics.defense.update', $topic) }}">@csrf @method('PUT')
<div class="mb-3"><label class="form-label" for="defended_at">Datum odbrane</label><input class="form-control @error('defended_at') is-invalid @enderror" id="defended_at" name="defended_at" type="date" max="{{ now()->format('Y-m-d') }}" value="{{ old('defended_at', now()->format('Y-m-d')) }}" required>@error('defended_at')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-3"><label class="form-label" for="president_id">Predsednik komisije</label><select class="form-select @error('president_id') is-invalid @enderror" id="president_id" name="president_id" required><option value="">Izaberite profesora</option>@foreach($professors as $professor)<option value="{{ $professor->id }}" @selected(old('president_id') == $professor->id)>{{ $professor->professorProfile->academic_title }} {{ $professor->name }}</option>@endforeach</select>@error('president_id')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="mb-4"><label class="form-label" for="member_ids">Članovi komisije</label><select class="form-select @error('member_ids') is-invalid @enderror" id="member_ids" name="member_ids[]" multiple size="6" required>@foreach($professors as $professor)<option value="{{ $professor->id }}" @selected(in_array($professor->id, old('member_ids', [])))>{{ $professor->professorProfile->academic_title }} {{ $professor->name }}</option>@endforeach</select><div class="form-text">Držite Ctrl ili Command za izbor više članova. Potreban je najmanje jedan član.</div>@error('member_ids')<div class="invalid-feedback">{{ $message }}</div>@enderror</div>
<div class="alert alert-info"><i class="bi bi-info-circle me-1"></i> Potvrdom se status rada trajno menja u „Odbranjena“.</div><div class="d-flex justify-content-end gap-2"><a class="btn btn-light" href="{{ route('topics.show', $topic) }}">Odustani</a><button class="btn btn-primary">Potvrdi odbranu</button></div>
</form></div></div>
@endsection
